export * from './contracts/index.js';
export * from '../application/services/ImportantMemoryService.js';
export * from '../application/services/PeopleDirectoryService.js';
export * from '../domain/entities/Person.js';
export * from '../domain/services/PersonIdentityMatcher.js';
export * from '../infrastructure/persistence/PeopleRepository.js';
export * from '../module/PeopleMemoryModule.js';
export * from '../module/PeopleMemoryModuleFactory.js';
export * from '../module/PeopleMemoryModuleConfig.js';
